# Generated by Django 5.1.1 on 2024-09-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_restaurant_remove_review_user_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewer'),
        ),
    ]
